### ISSUE TITLE
I am rlly jelly

### ISSUE THREAD

**Issue by LiEnby** [SKGleba/psp2hfw#2]
like really, my iq is < 89

**Comment by SKGleba** [comment]
Hey "silica", github is 13+ and 90iq+, i am afraid that you didnt qualify.

**Comment by KuromeSan** [comment]
OMFG SKG IS CENSORING THE FACT HIS SOFTWARE BRICCS! 
SAYING ITS INVALID.. smh

like litterally my system bricked when i ran this on my PDEL-1001 ..

**Comment by teakhanirons** [comment]
So i installed this @@@@@ hfw and it fk@@ deleted everything in my ps vita including sd2vita plugin so i cant use my ps vita anymore i need someone to take blame and responsibility for this stupid plugin

**Comment by KuromeSan** [comment]
https://www.youtube.com/watch?v=Ij5WNcaAP5Y this is what it did to my PDEL1001 console. and @SKGleba tries to hide it!
